language: go
go: 
 - 1.5.1
 - release
 - tip
sudo: false
before_script:
  #- go vet ./...
script:
 - go test -v ./...
install:
  # Add Godeps dependencies to GOPATH and PATH
  #- export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  #- export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  
after_success:
# notify Docker Hub to make a new build
- >
  [ "$TRAVIS_BRANCH" == "master" ]
  && curl -X POST -H "Content-Type: application/json"
  --data '{"docker_tag_name": "latest"}'
  https://registry.hub.docker.com/u/dockingtools/register/trigger/$DOCKER_HUB_TOKEN/  